version: '3.8'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env.local
    ports:
      - "3306:3306"