version: '3.8'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
  
  dbgui:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    env_file:
      - .env
    environment:
      PMA_HOST: db
      PMA_USER: root
    ports:
      - "8080:80"